name: flatland-rl
channels:
  - defaults
dependencies:
  - certifi=2021.5.30
  - pip=21.0.1
  - python=3.6.13
  - setuptools=58.0.4
  - wheel=0.37.0
  - python-graphviz=0.17
  - pip:
    - argon2-cffi==21.1.0
    - async-generator==1.10
    - atomicwrites==1.4.0
    - attrs==21.2.0
    - backcall==0.2.0
    - backports-entry-points-selectable==1.1.0
    - bleach==4.1.0
    - cffi==1.14.6
    - charset-normalizer==2.0.6
    - click==8.0.1
    - cloudpickle==1.2.2
    - colorama==0.4.4
    - crowdai-api==0.1.22
    - cycler==0.10.0
    - dataclasses==0.8
    - decorator==4.4.2
    - defusedxml==0.7.1
    - distlib==0.3.3
    - entrypoints==0.3
    - filelock==3.3.0
    - flatland-rl==3.0.8
    - future==0.18.2
    - gym==0.14.0
    - idna==3.2
    - imageio==2.9.0
    - importlib-metadata==4.8.1
    - importlib-resources==1.5.0
    - ipycanvas==0.9.0
    - ipykernel==5.5.5
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter-client==7.0.5
    - jupyter-core==4.8.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.1
    - lxml==4.6.3
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - more-itertools==8.10.0
    - msgpack==0.6.1
    - msgpack-numpy==0.4.7.1
    - nbclient==0.5.4
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - notebook==6.4.4
    - numpy==1.19.5
    - packaging==21.0
    - pandas==1.1.5
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pickleshare==0.7.5
    - pillow==8.3.2
    - platformdirs==2.4.0
    - pluggy==0.13.1
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - protobuf==3.18.0
    - py==1.10.0
    - pyarrow==5.0.0
    - pycparser==2.20
    - pyglet==1.3.2
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - pytest==4.6.11
    - pytest-runner==5.3.1
    - python-dateutil==2.8.2
    - python-gitlab==2.10.1
    - pytz==2021.3
    - pyzmq==22.3.0
    - recordtype==1.3
    - redis==3.5.3
    - requests==2.26.0
    - requests-toolbelt==0.9.1
    - scipy==1.5.4
    - send2trash==1.8.0
    - six==1.16.0
    - svgutils==0.3.4
    - tensorboardx==2.4
    - testpath==0.5.0
    - timeout-decorator==0.5.0
    - toml==0.10.2
    - torch==1.9.1
    - torchvision==0.10.1
    - tornado==6.1
    - tox==3.24.4
    - traitlets==4.3.3
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - virtualenv==20.8.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.6.0